name=DevelDeckAPI
version=0.2.1
author=DevelTeam
maintainer=DevelTeam
sentence=Framework for DevelDeck by DevelTeam
paragraph= 
category=ESP32
url=https://github.com/AlexeysShelyagin/DevelDeckAPI
architectures=*
includes=DevelDeckAPI.h
